### ISSUE TITLE
Subviews with marionette

### ISSUE THREAD

**Issue by VictorChen** [rotundasoftware/backbone.subviews#23]
Is this suppose to work with Marionette views?

If so, it seems like it doesn't clean up the Marionette subviews correctly.

https://github.com/rotundasoftware/backbone.subviews/blob/master/backbone.subviews.js#L52

It calls `view.remove();` when cleaning up the subviews, but if the subviews are marionette views, then I would expect it to call `view.destroy();`.

**Comment by dgbeck** [comment]
Hi Victor,

Thanks.. you bring up a good point.

Backbone.Subviews is not designed for Marionette. We would like the two to play nicely together but I would rather not go down the path of building in special cases for particular frameworks, especially since other frameworks generally offer constructs that are kind of analogous to Backbone.Subviews.

For now, if you want to use the two together and need the extra bells and whistles offered by the `destroy` method (i.e. `destroy` events and behavior cleanup) feel free to override `view.removeSubviews` and change `thisSubview.remove()` to `thisSubview.destroy()` as you suggest.

Thanks again for putting this issue on the radar.
